### ISSUE TITLE
melspecgan generator

### ISSUE THREAD

**Issue by geshumin** [paarthneekhara/advoc#14]
Excuse me. When i reading you web page, you said "first training a GAN to generate mel spectrograms (MelSpecGAN) and then training an adversarial vocoder to vocode those spectrograms into audio". But i really do not know how to do the two steps , Please can you tell me some details? thank you so much!

**Comment by chrisdonahue** [comment]
Sorry, we released this codebase a little prematurely. We have overhauled the README. Closing this for now; please let us know if this answers your question!

**Comment by geshumin** [comment]
Thank you for all your replies. I really like your ideas. Thanks again!

At 2019-04-18 02:18:57, "Chris Donahue" <notifications@github.com> wrote:


Sorry, we released this codebase a little prematurely. We have overhauled the README. Closing this for now; please let us know if this answers your question!
